### ISSUE TITLE
!stupid

### ISSUE THREAD

**Issue by MrC74rk** [CodeCulture-io/discord#15]
## Custom user command to make Mee6 post the gif below
![image](https://user-images.githubusercontent.com/45373566/90344091-ff2a1000-dfdb-11ea-8301-77348ed8320f.png)

Brief explanation of the feature.

### Self Explanitory

What is your idea, project, effort, or other bit you would like to add to the community. 

### To reduce the amount of mung that presents itself in the form of stupid comments. 

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by mkylemueller** [comment]
You should have access to mee6 dashboard

**Comment by mkylemueller** [comment]
@MrC74rk can you link to the actual gif the one posted is only single frame

**Comment by MrC74rk** [comment]
I don't seem to have access. The only bot I can see on the dashboard is the on in my personal discord.

**Comment by mkylemueller** [comment]
I'll look later battery is about to die as why you don't have access but I have added `!stupid` to mee6 bot
