### ISSUE TITLE
!ui-ideas

### ISSUE THREAD

**Issue by dinoknowsbetter** [CodeCulture-io/discord#20]
## Summary

Returns a list of websites the community uses for front-end inspiration.

### Basic example

**User:** _!ui-ideas_

**Response:** _Dribbble, Behance, Google, UI8.net, etc._

### Motivation

The question gets asked at least 5 times a week. This saves time and energy.

**Comment by mkylemueller** [comment]
added, if it becomes more area of request let's make a dedicated page to it.
